### ISSUE TITLE
Unable to build this last version

### ISSUE THREAD

**Issue by raphaelkong** [EnterpriseDB/mysql_fdw#79]
Hi,
I'm no more able to build the extention ; my last try was this morning, and it fails
Here is the error : 
<pre>
mysql_fdw.c: In function \u2018mysqlGetForeignPaths\u2019:
mysql_fdw.c:913:11: error: too many arguments to function \u2018create_foreignscan_path\u2019
           NULL)); /* no fdw_private data */
           ^
In file included from mysql_fdw.c:39:0:
/usr/include/postgresql/9.4/server/optimizer/pathnode.h:80:21: note: declared here
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
make: *** [mysql_fdw.o] Erreur 1
</pre>

Ubuntu 14.04
Postgresql 9.4

Thx !
Raphael.

**Comment by ibrarahmad** [comment]
I have pushed the fix, please try now. This error was introduced by this
pull request "Fix build with postgres 9.5 #78"


On Tue, Dec 29, 2015 at 5:55 PM, Raphael <notifications@github.com> wrote:
>
> Hi,
> I'm no more able to build the extention ; my last try was this morning,
and it fails
> Here is the error :
>
> mysql_fdwc: In function \u2018mysqlGetForeignPaths\u2019:
> mysql_fdwc:913:11: error: too many arguments to function
\u2018create_foreignscan_path\u2019
>            NULL)); /* no fdw_private data */
>            ^
> In file included from mysql_fdwc:39:0:
> /usr/include/postgresql/94/server/optimizer/pathnodeh:80:21: note:
declared here
>  extern ForeignPath *create_foreignscan_path(PlannerInfo *root,
RelOptInfo *rel,
>                      ^
> make: *** [mysql_fdwo] Erreur 1
>
> Ubuntu 1404
> Postgresql 94
>
> Thx !
> Raphael
>
> —
> Reply to this email directly or view it on GitHub.




--
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by raphaelkong** [comment]
Nice !
It builds now !
Thx for your quick fix :]
